### PR TITLE
Ensure StateChange are posted in order to Handler

### LINKED ISSUE #11: Switching state not ordered
When a node switches state, it invokes `go n.handler.StateChange(old, state)` in `switchState`, this is wrong since it does not guarantees the order of the state changes. If in time a node goes from FOLLOWER to CANDIDATE and then CANDIDATE to LEADER, the state change channel may end-up having the two state changes reversed due to the execution of a go routine to report the change of the state.

### PR DESCRIPTION
**Pull request by kozlovic**
This is another approach for solving issue #11 that was addressed
with PR #12. The advantage of this approach over #12 is that there
will be atmost 1 go-routine per type of event (StateChange and error).

Added a test that demonstrates that not receiving from state change
and error channels do not block the Node.

Also fixed a flapping test.

Resolves #11

### CODE REVIEW

File: handler_test.go [hunk 1]
```diff
@@ -7,7 +7,9 @@ import (
 	"testing"
 	"time"
 
+	"fmt"
```
Comment (derekcollison) [inline handler_test.go]: sort these, all pkg ones at top and 3rd party separated by line space and at the bottom.

File: node.go [hunk 2]
```diff
@@ -546,9 +571,13 @@ func (n *Node) switchState(state State) {
...
 	old := n.state
 	n.state = state
-	n.serializeGoRoutine(&n.stateChain, func() {
-		n.handler.StateChange(old, state)
-	})
+	sc := &StateChange{From: old, To: state}
+	n.stateChg = append(n.stateChg, sc)
+	// Invoke postStateChange only for the first state change added.
+	// Check postStateChange for details.
+	if len(n.stateChg) == 1 {
```
Comment (derekcollison) [inline node.go]: Can this change again before you check the length?

Comment (kozlovic) [inline node.go]: No it can't, we are under the node's lock when adding, checking and removing.

File: handler_test.go (hunk 1 above)
Comment (kozlovic) [inline handler_test.go]: Sorry about that. The IDE is integrated with go fmt, etc.. and usually orders correctly those. Not sure what happened.

File: node.go (hunk 2 above)
Comment (derekcollison) [inline node.go]: ok!
