### PR TITLE
[FIXED] Ensure state changes are posted in order they occur

### LINKED ISSUE #11: Switching state not ordered
When a node switches state, it invokes `go n.handler.StateChange(old, state)` in `switchState`, this is wrong since it does not guarantees the order of the state changes. If in time a node goes from FOLLOWER to CANDIDATE and then CANDIDATE to LEADER, the state change channel may end-up having the two state changes reversed due to the execution of a go routine to report the change of the state.

### PR DESCRIPTION
**Pull request by kozlovic**
Both state changes and errors were posted through the use of a go
routine. This did not guarantee that the changes would arrive in
the state change handler in the same order they were produced.

Resolves #11

### CODE REVIEW

File: node.go [hunk 1]
```diff
@@ -36,6 +36,10 @@ type Node struct {
 	// Async handler
 	handler Handler
 
+	// Used to chain go routines posting events to async handler.
+	nextSCCh  chan bool
```
Comment (derekcollison) [inline node.go]: maybe nextStateChg

Comment (kozlovic) [inline node.go]: Sure. I was trying to keep it small. It standed for `next State Change Channel`

File: node.go [hunk 2]
```diff
@@ -514,6 +520,20 @@ func (n *Node) switchToCandidate() {
 	n.switchState(CANDIDATE)
 }
 
+// Execute `f` in a separate go routine, but ensures that functions
+// are executed in order.
+func (n *Node) serializeGoRoutine(nextCh *(chan bool), f func()) {
```
Comment (derekcollison) [inline node.go]: So this can only handle two channels at most correct? Might want to document if that is the case.

Comment (derekcollison) [inline node.go]: Should we make it generic where their is a list of channels you can select from?

File: node.go (hunk 1 above)
Comment (derekcollison) [inline node.go]: Took me awhile to figure that out.. ;) That is why I suggested something more descriptive but still short. Maybe just stateChg?

File: node.go (hunk 2 above)
Comment (kozlovic) [inline node.go]: No, because the node creates a `nextChannel` every time, and pass it as a closure to the function.

Comment (derekcollison) [inline node.go]: So we have N Go routines they are just chained together correct? Feels like we should be able to do with 1 Go routine correct?

Comment (kozlovic) [inline node.go]: The goal is to not block the node when posting a state change (or error). The default StateChange handler is channel based, and unbuffered (not a solution anyway). If the user is not dequeuing, the node could be blocked.
Options are for the node to have a single go routine but use an array or list of events that are added and notify the central go routine doing the dispatching.
I feel that in this case, the proposed solution is elegant and simpler. I don't think we can expect thousands of changes a second ;-). But we do want changes to be added to the handler in order. What do you think?

Comment (derekcollison) [inline node.go]: I hear you, just concerned that we have N Go routines that are lock stepped instead of one that is selecting from multiple channels. But your solution may be better.

Comment (kozlovic) [inline node.go]: Let me experiment. I will let you know when ready for review, ok?

Comment (derekcollison) [inline node.go]: Yes sounds good.

**Comment by kozlovic** [comment]
There are 2 commits, 1 for a fix to first implementation (and rename variables). The second is using a single go-routine. I will let you decide which one you prefer.

**Comment by derekcollison** [comment]
ok so I merged the other, but should I merge this one?

Which one is this?

**Comment by kozlovic** [comment]
This one is for the state change ordering issue. Originally go routines would be started and chained together. You were concerned about the number. The current code shows how we could do with a single go routine (and array of functions).

**Comment by derekcollison** [comment]
Which do you prefer?

**Comment by kozlovic** [comment]
I personally prefer the first one. Simpler and I believe perfectly fine for the use case (don't think there would be too many events).

**Comment by kozlovic** [comment]
Regardless, chose and let me know. I will then need to rebase master and do some cleanup (squash/force commits).

**Comment by derekcollison** [comment]
Let's go with your suggestion.. thx..

**Comment by kozlovic** [comment]
Ok, good to go here.
